esphome:
  name: devkitv1
  friendly_name: DevkitV1

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "UNnxzYb7+im19jDx5J6eSCquwT4G/epiR8yzjxyOflE="

ota:
  - platform: esphome
    password: "262c081c246922944a345d027890d194"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Devkitv1 Fallback Hotspot"
    password: "BEpOqEjSXdXV"

captive_portal:

switch:
  - platform: gpio
    pin:
      number: GPIO02
    id: gpio_led
    name: "DevkitV1 LED"

bluetooth_proxy:
  active: true

binary_sensor:
  - platform: ble_presence
    device_class: presence
    mac_address: D4:8A:FC:60:B8:86
    name: ESP32DevkitV1

sensor:
  - platform: template
    name: "ESP32Devkit1 Battery"
    icon: mdi:battery-bluetooth-variant
    unit_of_measurement: "%"
    accuracy_decimals: 0
    id: esp32devkit1_battery

esp32_ble_tracker:
  on_ble_manufacturer_data_advertise:
    - mac_address: D4:8A:FC:60:B8:86
      manufacturer_id: 09A3
      then:
        - lambda:
            id(esp32devkit1_battery).publish_state(x[0]);

# Reference:
# https://esphome.io/components/sensor/index.html
# https://esphome.io/components/sensor/template.html
